const EVENT_NAME = {
    SIGN_UP: 'SIGN_UP',
    JOIN_TABLE: 'JOIN_TABLE',
    GAME_STATUS: "WINNER",
    ROUND_TIMER: 'ROUND_TIMER',
    PLAY_GAME: "PLAY",
    CHECK_TURN:"CHECK_TURN",
    PRINT_VALUES:"PRINT_VALUES",
    WINNER:"WINNER",
    CHANGE_TURN:"CHANGE_TURN",
    REJOIN_GAME:"REJOIN_GAME",
}

export { EVENT_NAME }