const QUEUE_EVENT = {
    ROUND_TIMER: "ROUND_TIMER",
    RE_START: "RE_START",
    LEAVE_BUTTON: "LEAVE_BUTTON",
    TURN_TIMER: "TURN_TIMER",
    BOT_TIMER: "BOT_TIMER",
    PLAY_BOT: "PLAY_BOT",
}

export { QUEUE_EVENT }